### ISSUE TITLE
keep app open when no sessions are connected

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#104]
When doing oncall work, I often end up with a bunch of tabs open to different hosts.
When I'm done with a host, I tend to close the tab. 
It looks like when I close the last tab the app shuts down, so the next one I open takes longer to start up.

Would be nice if the app could stay around in the tray, or even just a window with no tabs, so that doesn't happen unless I explicitly close it.

**Comment by MaxRis** [comment]
Spawned process really still seats in the tray after UWP app exits. But longer startup time is there, seems, because of the reason you have described - UWP app process is starting up from the ground.

I guess, Settings option to not close the UWP app after last tab is closed might help there. But because single opened session doesn't have button to close it (only button to close whole application window is available) some redesign is required.

**Comment by cjw296** [comment]
Yeah, see https://github.com/jumptrading/FluentTerminal/issues/105 for some related stuff...

**Comment by daviesalex** [comment]
Reviewing older tickets I notice that in the current release from process closed to entirely new terminal via mosh (including SSH auth) for me probably takes 1 second, perhaps even less. If Fluent is running perhaps we get this down a tiny bit, but I think that this is totally acceptable and most of the time here is going to be the SSH auth (or terminal spawn for local) rather than Fluent itself.
