### ISSUE TITLE
Chrome style "drag window out" experience

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#109]
Some users want more than one window (rather than tabs). Ideally a Chrome style "drag window out" experience.

**Comment by MaxRis** [comment]
@daviesalex CTRL+SHIFT+N and CTRL+ALT+N are default shortcuts to launch new terminal session in new separate window.

> Ideally a Chrome style "drag window out" experience.
That sounds great to have implemented!

**Comment by cjw296** [comment]
I'd love the Chrome style "drag window out" experience.

**Comment by mjs** [comment]
This relates to this upstream issue: https://github.com/felixse/FluentTerminal/issues/44

**Comment by enigmeow** [comment]
Since under the covers it is using a common service to talk to the remote processes,  even if we didn't want to create a whole GUI that allows for docking and undocking...    a keyboard sequence that pops a tab out to a new window or moves tabs between windows should be much easier..

I find myself wanting to consolidate a bunch of windows/tabs or break a tab out so that I can see two terminals at the same time...

**Comment by MaxRis** [comment]
And related to https://github.com/jumptrading/FluentTerminal/issues/105

**Comment by MaxRis** [comment]
Going to take a look into this. cc: @peske

**Comment by MaxRis** [comment]
Update:

Someone published link to their work on XTerm.JS addon to do serialization of terminal state https://github.com/JavaCS3/xterm.js/commit/36d03546fc758c378c50c30e95a548dd119965bc

The roadmap is more clear now:

- Upgrade to XTerm.JS v4 beta

- Incorporate / use XTerm.JS addon for serialization

- Implement TabView and required tabs tear-off logic to play well with Fluent architecture

**Comment by peske** [comment]
My comment on this issue: https://github.com/felixse/FluentTerminal/issues/44#issuecomment-509033419

I'm not sure if we actually have to run windows in separate threads. Just as an example: last year I've created multi-window WPF charting app (and all windows in WPF app share the same UI thread), where every window contained multiple chart panes, every chart pane contained multiple series, in total 1M+ data points, and it runs pretty smoothly. Even sharing mouse position, cross-hair, showing tooltips simultaneously in all windows... Looking from this perspective, our UI is quite simple (although I don't know how demanding WebView is). But if we could run all the windows in the same UI thread, we would be able to drag and drop tabs between the windows without any serialization.

**Comment by mjs** [comment]
@MaxRis has been making good progress with this. I've just tried out https://github.com/MaxRis/FluentTerminal/tree/mr/web-browser-like-tabs-upstream and I have some feedback. Overall it's looking very promising.

**To address before proposing upstream**

- xtermjs serialization isn't preserving everything
  - Colours aren't preserved a tab is dragged out or moved to another window. For example: the default WSL shell prompt uses colour, but the terminal is monochrome after it is moved. 
  - Rendering glitches after a tab is moved. For example if htop is running in a tab and it is dragged out, various bits of the output are lost including htop's bottom status line. This doesn't appear to recover when htop refreshes. You have to stop and restart htop.
- We should talk to @felixse about removing the "Always show tabs" option or at least changing the default for this option. With this off you can't move a lone tab in a window to another window, nor can a window with one tab be a target for other tabs. This just feels like a weird restriction to have.

If the serialisation issues are going to take a while to resolve we could look to merge the current changes but hide them behind a "Allow tabs movement between windows (experimental)" option which is off by default. This will at least get the bulk of the code in and may encourage help from other contributors.

** Nice to fix but not critical for the initial PR **

- If the mouse goes over an active terminal window while a tab is being dragged, events are sent to that terminal causing it to scroll. This is unexpected and almost certainly not what you want.
- Finding the right place to drop a tab when reordering tabs is a little tricky. You do get used to it but it's hard at first. Can the zone where a tab can land be a little wider?
- Similarly it's hard to figure out where the tab is allowed to land when dragging from another window. Can the entire tab row area be a landing zone? This is how web browsers do it.

**Comment by MaxRis** [comment]
> Colours aren't preserved a tab is dragged out or moved to another window. For example: the default WSL shell prompt uses colour, but the terminal is monochrome after it is moved.

It's turned out that this information is not available via public API. Currently, only plain text from the buffer can be retrieved, but internally available `_data` https://github.com/xtermjs/xterm.js/blob/27d724a13aeb8366195caa965f9cd1442c211d31/src/common/buffer/BufferLine.ts#L56 can be used to get colors data per each cell.

If we absolutely need this resolved, it should be possible to fork xterm.js and extend it with our own public API.

**Comment by MaxRis** [comment]
> We should talk to @felixse about removing the "Always show tabs" option or at least changing the default for this option. With this off you can't move a lone tab in a window to another window, nor can a window with one tab be a target for other tabs. This just feels like a weird restriction to have.

"Always show tabs" option is turned on by default now.

**Comment by MaxRis** [comment]
> Rendering glitches after a tab is moved. For example if htop is running in a tab and it is dragged out, various bits of the output are lost including htop's bottom status line. This doesn't appear to recover when htop refreshes. You have to stop and restart htop.

Refreshing of htop (under WSL) works great for me with CTRL-L shortcut, not needed to restart htop.
Here is the same issue with full screen state restoring - we need a way to serialize and restore colors per each terminal cell.

Bottom status line seems is not get serialized because current logic serializes everything in buffer till the line with active cursor. Might makes sense to try to change the logic to RTrim all whitespaces and new lines.

**Comment by MaxRis** [comment]
> If the mouse goes over an active terminal window while a tab is being dragged, events are sent to that terminal causing it to scroll. This is unexpected and almost certainly not what you want.

Scrolling, seems, happens because of [overflow-y: scroll](https://github.com/xtermjs/xterm.js/blob/master/css/xterm.css#L96). Pointer hovering with pressed mouse button in front of scroll bar edges causes not desired scrolling. `scroll` value can be changed to 'hidden' to remove scrolling, but in that case scroll bar control will not be rendered by WebView if scrollbar visibility is set to "always" in Fluent Settings.

Possible acceptable workaround is to disable mouse events propagation into WebView control if drag of tab was started by user. Unfortunately, I was not able to find required UWP API that can help to achieve ignoring of mouse events by specific control and while some condition is set.

**Comment by MaxRis** [comment]
> Finding the right place to drop a tab when reordering tabs is a little tricky. You do get used to it but it's hard at first. Can the zone where a tab can land be a little wider?
Similarly it's hard to figure out where the tab is allowed to land when dragging from another window. Can the entire tab row area be a landing zone? This is how web browsers do it.

Going to investigate this. That might be not easy to improve as well.
Current "wrong behavior" is that if you drop to another window, it always adds dropped item to the end of the list (but reordering inside same window works good).
Interesting that official [drag and drop sample](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/XamlDragAndDrop) has the same issue - dropped item is added into the end of the list.

**Comment by MaxRis** [comment]
The request that sounds as the most doable as for me for now is to preserve dropped item screen coordinates to open new Window there https://github.com/jumptrading/FluentTerminal/issues/163

**Comment by mjs** [comment]
> > Rendering glitches after a tab is moved. For example if htop is running in a tab and it is dragged out, various bits of the output are lost including htop's bottom status line. This doesn't appear to recover when htop refreshes. You have to stop and restart htop.
> 
> Refreshing of htop (under WSL) works great for me with CTRL-L shortcut, not needed to restart htop.

Right - Ctrl-L in WSL works. I was trying FluentTerminal's redraw command (Ctrl-Alt-L) which doesn't help.

> Here is the same issue with full screen state restoring - we need a way to serialize and restore colors per each terminal cell.

Got it.

> Bottom status line seems is not get serialized because current logic serializes everything in buffer till the line with active cursor. Might makes sense to try to change the logic to RTrim all whitespaces and new lines.

That's worth a try.

**Comment by mjs** [comment]
I've separated out the remaining work into their own Github Issues. Given that the bulk of this feature has landed I'm closing this one.
