### ISSUE TITLE
ssh dialog should remember previous hosts I have ssh'd to so that I can connect faster

### ISSUE THREAD

**Issue by enigmeow** [jumptrading/FluentTerminal#116]

**Comment by cjw296** [comment]
Yes, please! I thought I put in an issue about this too but I can't find it.
I'd really like some kind of "quick connect" I could bring up with a key binding and then behave like the chrome address bar when it comes to remembering stuff I've typed in it before.

It would be powerful if "stuff" could be the full url, with options:

```
ssh://somehost
mosh://someuser@somehost
ssh://user@host? <not sure how to put -L options in here...)
```

**Comment by mjs** [comment]
I've moved @cjw296 's request here to #121

**Comment by peske** [comment]
Replying to the original @enigmeow's comment:

Making "SSH Info" remember the last used configuration can be done. Not sure how useful it'll be (since we have "Save shortcut" and "SSH Profiles"), and even if it can be annoying if you need to change everything. But if you guys decide - I can implement _remember-prefill_.

Regarding the last part of @cjw296's comment, related to `-L` option - it's covered in https://github.com/jumptrading/FluentTerminal/issues/117

**Comment by cjw296** [comment]
I suspect what after here is not just filling in the host with the last used host, but a blank box with a [freceny ](https://en.wikipedia.org/wiki/Frecency) dropdown of things that you've connected to before, much like macOS Terminal does.

**Comment by mjs** [comment]
The remaining part is covered by #148
