### ISSUE TITLE
Let me port forward in both directions using Fluent 

### ISSUE THREAD

**Issue by enigmeow** [jumptrading/FluentTerminal#117]

**Comment by cjw296** [comment]
Yes please!

**Comment by peske** [comment]
Not sure for others, but I don't understand this one at all. Some additional explanation would be good.

**Comment by cjw296** [comment]
This is basically offering the equivalent of the CLI ssh's `-L` option:

```
ssh -L 8080:localhost:80
```

**Comment by peske** [comment]
OK, now I understand. There are two possible ways to provide this feature, and in this comment I'll explain the first one.

We can add another **table-like list box** to both "SSH Info" adhoc dialog, and in "SSH Profile" configuration page. The user will be able add SSH configuration **key-value pairs** to the list, as needed. SSH options that can be configured this way are enumerated [here](https://man.openbsd.org/ssh#o) - dozens of options are available there.

The user doesn't have to specify all these options, of course - only needed one. For the particular issue described here, you should probably specify [`LocalForward`](https://man.openbsd.org/ssh_config.5#LocalForward) and [`RemoteForward`](https://man.openbsd.org/ssh_config.5#RemoteForward).

To explain: it's kinda difficult for us to implement CLI arguments properly (like `ssh -L 8080:localhost:80`) because they may overlap with the existing things we generate (i.e. `user@host:port`). But the good thing is that probably all CLI arguments have their corresponding SSH config key-value, which we can add.

**Comment by peske** [comment]
The second option would be _manual_. It would work something like:

Add "Manual Arguments" button to "SSH Info" dialog and "SSH Profile" configuration page, and when user clicks it - very simple dialog opens which allows you to enter all SSH CLI arguments (everything that goes after SSH.exe). In this case the user would have to enter everything manually, including username, host, port, etc.
So guys, let me know what do you think about these. @daviesalex, @enigmeow, @cjw296?

**Comment by peske** [comment]
Also, it's worthwhile mentioning that such things wouldn't have effect on mosh.

**Comment by mjs** [comment]
The third option would be to add port forwarding as a first class option (i.e. with its own dedicated UI). This could be worthwhile if this is a commonly used feature. @daviesalex, @enigmeow and @cjw296: some guidance on what you'd prefer would be helpful here.

**Comment by enigmeow** [comment]
The use case is as follows.  I want to ssh into machine and use X11 port forwarding to send a x window back to my desktop.  I want to leverage the mosh infrastructure so that if I switch networks or disconnect for an extended period of time, I don't lose my X11 applications.

At present, I use a custom solution that maintains virtual tcp connections during disconnects but that means I am using two solutions instead of one

**Comment by daviesalex** [comment]
Thats a very different problem thank mosh itself solves - its not even as simple as encapsulating TCP inside UDP because the TCP session will timeout so you need a sort of TCP "proxy" that keeps 2 connections open at each end and then does best effort updates between them.

We can backlog this task, but if we do this its going to be a separate binary that runs both on the client and server and will only work for some TCP connections (ones that dont do any application level heartbeating).  I do wonder if there is a better solution to this (like auto-reopening the X windows in the right place) for your specific use case.

**Comment by cjw296** [comment]
Yeah, port forwarding over mosh sounds like it should be a separate issue on this tracker?

`-L` for ssh would be good, again, I have to admit a preference for the macOS Terminal approach of a single text box you just type in rather than an array of separate gui widgets I have to click and tab through.

**Comment by peske** [comment]
Conclusions:
1. It's SSH-only.
2. Adding `-L` argument wouldn't be too complicated. I can add "Additional CLI arguments" field to "SSH Info" dialog, and you can write `-L 8080:example.com:80` there (or even `-L 8080:example.com:80 -L 12345:example2.com:80`). And I can add similar field to "SSH Profiles" settings page.
3. I can additionally create another, single-text-box dialog (as @cjw296 wants), so that you can write everything there, like `-L 8080:example.com:80 user@host`

And all this will work with ad-hoc dialogs and with SSH Profiles (you'll be able to save).

Bigger problems are shortcuts (solvable, but may take more time). If you want to save such thing as a shortcut (link), and if we want that link to be compliant with `ssh://` standard, I would have to do some conversion. For example, command: 
`ssh -L 8080:example.com:80 user@host` 
should be converted to:
`ssh://user;LocalForward=8080%20example.com%3A80@host`
Such link would be standard, meaning that any other app that can open `ssh://` links will be able to _understand_ it.

Of course, It'll be much faster if we disable shortcuts for such custom cases, or if we ignore standards, meaning that only Fluent will be able to understand.

Sorry for long description, but I have to explain you the problem, so that you can tell me which way to go.

**Comment by peske** [comment]
In short, options are:
- Ignore shortcuts for now;
- Go full (will take much more time to predict all CLI options).

**Comment by peske** [comment]
We've agreed to start simple, without support for links/shortcuts with `-L` options.

**Comment by cjw296** [comment]
Why don't these parameters just form part of the url?
`ssh://user@host:22?L=8080:localhost:80&L7022:196.18.1.12:22`

**Comment by peske** [comment]
@cjw296 `ssh://user@host:22?L=8080:localhost:80&L=7022:196.18.1.12:22` is not according to standards, so if we create it this way, it'll be usable only in Fluent.
The standard link with the same configuration would be:
```
ssh://user;LocalForward=8080%20localhost%3A80@host:22
```
And it looks complicated to write...

For this reason adding single text field where additional CLI arguments can be added (i.e. `-L 8080:locallhost:80`) is probably simpler for the user.

**Comment by cjw296** [comment]
Oh, interesting. I don't find that any more complicated that remembering `-L...` I guess we need to support this for SSH urls anyway, but yeah, I'd prefer a macOS-style text box...

**Comment by peske** [comment]
@cjw296 , can you please attach few screenshot of that macOS-style text box, or maybe even short video?

**Comment by cjw296** [comment]
@peske - you've pretty much described it exactly on https://github.com/jumptrading/FluentTerminal/issues/135. I haven't had much joy on attaching screenshots on GH, but I'll ping one into Slack.

**Comment by peske** [comment]
This issue is solved by implementing "Quick SSH".
