### ISSUE TITLE
Single-text-box dialog

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#135]
I've noticed that a similar thing reappears through several issues here ([quick connect](https://github.com/jumptrading/FluentTerminal/issues/121), [port forward](https://github.com/jumptrading/FluentTerminal/issues/117), [host from standard config](https://github.com/jumptrading/FluentTerminal/issues/132), and few times requested by @cjw296 single-text-box UI).

My proposition is to create another ssh connect dialog, which would contain only one text box, in which user can (and must) enter all CLI arguments which should go after `ssh.exe`. For example user can enter:
```
-L 8080:example.com:80 user@host:22
```
or in case of [host from standard config](https://github.com/jumptrading/FluentTerminal/issues/132), he can enter only:
```
dev
```
or even
```
-L 8080:example.com:80 dev
```
The user can enter **anything** that can be entered after `ssh` command.

Good thing is that such defined connection **can also be saved as SSH Profile** for future use.

Does this make sense?

**Comment by MaxRis** [comment]
Is it possible to embed such single text box inside usual SSH dialogs and dynamically switch controls layout based on selected mode to enter SSH information - "full command line in text" or in separate controls (as it's done currently)?
As for me, possibility to enter full command line copied from somewhere is a missed feature. Just yesterday have tried to connect to EC2 instance and it was needed to split SSH connection string provided by website into separate components to be copy/pasted one by one (username, hostname, identity path).

**Comment by cjw296** [comment]
Yes, this is perfect :-) (ie: make it behave like a command launcher, ideally for mosh, ssh, etc)

**Comment by peske** [comment]
@MaxRis - yes, this is pretty much it.

**Comment by peske** [comment]
The biggest part of this feature is now implemented in https://github.com/felixse/FluentTerminal/pull/423. Actually, the only thing that isn't implemented yet is auto-complete.

Once the PR gets merged, "Quick SSH" dialog will be available on Ctrl+Shift+Q or Ctrl+Alt+Q.

**Comment by peske** [comment]
Let me repeat my question from Slack:

It isn't hard to add new command in UI, but the issue is what will the command do. `sh` command you've requested is unknown for Fluent (thus cannot be added to UI). 
Regarding `mosh`: @cjw296, can you please enter few complete examples of `mosh` command you would like to execute this way? I need to check what's possible because at the moment we're handling `mosh` on very basic level...

**Comment by mjs** [comment]
Following on from my feedback at https://github.com/felixse/FluentTerminal/pull/423...

After that pull request I think the following enhancements should be considered.

### Command History

This has already been requested elsewhere and will make the Quick SSH dialog so much more powerful. Implement this as a listbox or auto-completion dropdown containing command history with [frecency](https://en.wikipedia.org/wiki/Frecency) ordering.

### Mosh support

Support for mosh could be implemented by allowing commands such as `mosh username@host` and `mosh -i identify.file username@host`. Basically, just pass these commands through to mosh.exe.

Some thought needs to be put into how to handle if someone tries to use a SSH feature that doesn't work with mosh (e.g. port forwarding). The right way to handle this could be to have the mosh.exe detect unsupported options and have it return an error.

### Documentation

Due to the freeform nature of the text input, users are going to need some guidance about what is allowed. I suggest:
- Add a section in the README which explains the Quick SSH dialog
- Add a F1 binding to the dialog which open the relevant section of the README in a web browser
- Possibly also a `?` button next to the dialog which does the same.
- Add a tooltip for the text field which has a few concise but useful examples.

### Merge with/replace "SSH Info" dialog

The functionality of the "Quick SSH" and "SSH Info" dialogs overlaps directly and although both dialogs have their strengths, I don't think it makes sense to have both as separate features. Some possible ways of handling this:
- Add a way to switch the dialog between simple (SSH Info) and power (Quick SSH) modes. FT could remember which one the user last used and start in the last used mode when the dialog is activated
- Or, merge the features of both. That is, add the identity file controls and "Use Mosh" checkbox to the "Quick SSH" text field. Then:
  * If the `-i` option is used in the command text field, update the identity file control. If the identity file control is updated, reflect this in the command line.
  * if the "use mosh" checkbox is enabled, change the command in the command text field and vice versa.

I prefer the latter approach. It will be more work to implement but would be very slick, and also reduces the need for documentation - once users see the effect of updating the identity file control and "use mosh" checkbox it'll become clearer how to the command text box works.

**Comment by peske** [comment]
My answers to @mjs comments:

**Command history**
I 100% agree, and this is the plan. I already have some idea for _smart auto-complete_. Will play with that.

**Mosh support**
Of course it would be trivial for me to accept `mosh` commands in the format you've suggested - it's the format used by our wrapper. While creating the wrapper I've planned arguments so that they are convenient for us, but the problem is that this format **does not comply to any standard**. Regular users would more likely expect some standard `mosh` format (as described [here](https://mosh.org/#usage)) or `mosh-client` format (as described [here](https://www.systutorials.com/docs/linux/man/1-mosh-client/)).
For this exact reason I've asked @cjw296 for an additional explanation - to check what kind of command he would like to execute there. We need to plan this bit more carefully.

**Documentation**
I agree.

**Merge with / replace "SSH Info" dialog**
In my opinion we should keep both options - some users will prefer _rich UI_, others will prefer _single-line UI_. So I'm against _replacing_ "SSH Info".
On the other side, I agree that these two should be combined somehow, and my idea is to add an option like "Use quick SSH" to the top of the dialog, and based on the selection change the dialog content (current "SSH Info" content or "Quick SSH" content). I need the similar option in "Remote Profiles" page to be able to save single-line profiles. (At the moment single-line SSH cannot be saved in profiles.) 
We can also add a configuration option so that user can define which one will be shown by default.

But I'm strongly against combining "SSH Info" approach and "Quick SSH" approach, in a way you've suggested in your second point (like _single-line UI_ + "Use mosh" and "Identity file" fields). My primary reason to be against such thing is not in the additional work that needs to be done (it isn't too tough), but more in the fact that I don't like it. If we have a _reach UI_ option, and _custom command_ option - we don't need to have a third one in between. I believe that regular users either like UI ("SSH Info" input), or CLI ("Quick SSH" input), but no one some weird thing in between.

**Comment by mjs** [comment]
> **Mosh support**
> Of course it would be trivial for me to accept `mosh` commands in the format you've suggested - it's the format used by our wrapper. While creating the wrapper I've planned arguments so that they are convenient for us, but the problem is that this format **does not comply to any standard**. Regular users would more likely expect some standard `mosh` format (as described [here](https://mosh.org/#usage)) or `mosh-client` format (as described [here](https://www.systutorials.com/docs/linux/man/1-mosh-client/)).
> For this exact reason I've asked @cjw296 for an additional explanation - to check what kind of command he would like to execute there. We need to plan this bit more carefully.

Firstly, we don't want to accept `mosh-client`'s API. It's a low-level helper, not something that end users would normally interact with. 

Accepting arguments like the main mosh client makes sense as this will be most familar. Maybe our wrapper should be updated to behave more like standard mosh.

Input from Jump folks on this would be much appreciated.

> **Merge with / replace "SSH Info" dialog**
> In my opinion we should keep both options - some users will prefer _rich UI_, others will prefer _single-line UI_. So I'm against _replacing_ "SSH Info".
> On the other side, I agree that these two should be combined somehow, and my idea is to add an option like "Use quick SSH" to the top of the dialog, and based on the selection change the dialog content (current "SSH Info" content or "Quick SSH" content). 

This is basically my first proposal for merging the features. I'm fine with this if it's done tastefully and in a way that's not surprising to the majority of users.

> But I'm against combining "SSH Info" approach and "Quick SSH" approach, in a way you've suggested in your second point (like _single-line UI_ + "Use mosh" and "Identity file" fields). 

I'm happy to be guided what our users think here.

**Comment by peske** [comment]
Here's a short [video demo](https://youtu.be/U2RU-eP6v8w) of the current "Quick SSH" / "SSH Info" integration.

**Comment by peske** [comment]
I've broken this issue into three independent issues, to make things clearer:

- https://github.com/jumptrading/FluentTerminal/issues/148
- https://github.com/jumptrading/FluentTerminal/issues/149
- https://github.com/jumptrading/FluentTerminal/issues/150

I'm closing this one.
