### ISSUE TITLE
Dragging a tab over a terminal tab causes unwanted scrolling

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#165]
From #109:

If the mouse goes over an active terminal window while a tab is being dragged, events are sent to that terminal causing it to scroll. This is unexpected and almost certainly not what you want.

From @MaxRis:
> Scrolling, seems, happens because of [overflow-y: scroll](https://github.com/xtermjs/xterm.js/blob/master/css/xterm.css#L96). Pointer hovering with pressed mouse button in front of scroll bar edges causes not desired scrolling. `scroll` value can be changed to 'hidden' to remove scrolling, but in that case scroll bar control will not be rendered by WebView if scrollbar visibility is set to "always" in Fluent Settings.

> Possible acceptable workaround is to disable mouse events propagation into WebView control if drag of tab was started by user. Unfortunately, I was not able to find required UWP API that can help to achieve ignoring of mouse events by specific control and while some condition is set.

**Comment by MaxRis** [comment]
Since property to detect dragging started/stopped is [in place now](https://github.com/felixse/FluentTerminal/commit/71282eb65d75d8203ee91303aa8f9d1cef416251#diff-1c2f64b6341d1af922aac2c4a617406eR219), it should be possible to disable pointer events receiving by WebView with showing of another control surface while dragging happens.

**Comment by MaxRis** [comment]
Resolved by merging from upstream https://github.com/jumptrading/FluentTerminal/pull/191
