### ISSUE TITLE
Quick launch doesn't complete when selecting from list with mouse

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#185]
Quick connect looks great, but:

- type some stuff
- see the list appear
- try and select an item with the mouse

On 1.1.334.0, the select list just vanished without the text being pasted into the connect box.
If I navigate with the keys and hit enter, the text is pasted.

Somewhat related (please let me know if you want a separate issue), when I hit enter in the quick connect box, I expect the terminal to be launched. Currently, I have to hit enter again, which feels a bit weird.

**Comment by mjs** [comment]
This would be nice to fix. @peske can pick this up when he's back from leave.

**Comment by mjs** [comment]
Regarding the double enter thing, It bugs me too but the issue is that if you want to select an item from the list but then change some the settings in the Advanced section before running it, you wouldn't be able to to because hitting Enter immediately launched the command.

What about if we made something like Ctrl-Enter in the quick launch entry field trigger an immediate launch? That would be fairly intutitive and would avoid unexpected action when Enter (without a modifier) is used. If that works for you, please create a new issue for that.

**Comment by cjw296** [comment]
So, on the assumption that the Advanced section isn't the usual flow, I'd be fine with "hitting enter once" going through. If you want to use advanced stuff, use tab or click with the mouse. 

I think this UI pattern is pretty common and feels natural to people as it's what web apps and the like have been doing for years. That said, this feels like a separate issue. Do you like the idea? If so, I'll stick a ticket in...

**Comment by mjs** [comment]
@cjw296 ok sounds reasonable. Please create a separate issue.

**Comment by peske** [comment]
Solved in https://github.com/felixse/FluentTerminal/pull/579
