### ISSUE TITLE
split between "profiles" and "ssh profiles" feels weird.

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#195]
It feels like there should just be "profiles" with the ability to choose the connection method.

This isn't a big deal, just wanted to note it as it feels weird. There are some things you can do with profiles and not SSH profiles, and vice versa.

**Comment by mjs** [comment]
I'm not convinced it's worth putting in much work here - there would have to be more than just one user asking for this :)

**Comment by cjw296** [comment]
Re-opening after chatting with @mjs . @daviesalex, I think you found this a bit confusing too?

**Comment by mjs** [comment]
@peske how much effort do you think would be involved to present local and SSH profiles in the same UI?

**Comment by mjs** [comment]
@cjw296 @daviesalex aside from "feeling weird" what is the motivation for merging them into one concept? What would be the benefits?

Local and SSH profiles obviously require quite different inputs to define them. There would still need to be some way for users to say which kind of profile they wanted to create - possibly via separate "New Profile" and "New SSH Profile" buttons on the top of the Profiles section until Settings. At that point, why bother having them in the same section?

**Comment by mjs** [comment]
I'm just trying to make sure we don't spend a lot of development effort on something with minimal benefits.

**Comment by MaxRis** [comment]
I believe that initial implementation for remote profiles and local already were done in single list inside Settings, but later we decided to split it?
Possible disadvantage of keeping them separate might be unavailability to check all available Shortcuts for all profiles from the same list. What else is weird here?

**Comment by cjw296** [comment]
For me, conceptually, we have:

Generic Shell Preferences:
- Colour
- Key binding
- etc
- args to shell (overriding whatever comes from the shell-specific config)

Shell Type:
- mosh
- ssh
- docker
- git bash
- various custom (where I specify the shell binary)

Shell-specific config:
- mosh/ssh: you have a hostname, user, etc
- docker: (hypothetical) could specify image, container name and mounted volumes
- git bash: initial working directory

Some of these are mainly to show what could be done, but he above just feels more logical to me, I'd imagine it'd make the code cleaner and more flexible going forwards.

Whether this is worth doing is likely a function of how hard it is to do.

**Comment by daviesalex** [comment]
While I dont disagree that if I was starting from scratch, there is no obvious reason for the difference between local and remote, and one generic system that handles everything (not hugely dissimilar to the putty type model) may be more obvious. At the same time, I also am not totally convinced that this is worth fixing at this point. 

@felixse  I think this is mostly a question for you; what do you think?

**Comment by peske** [comment]
The reason why these are split is @felixse's requirement - even before we started working he planned to have SSH under "Remote Profiles". We had a quite intensive discussion on this subject in Slack at the time. I believe that @felixse's idea was to have "SSH Profiles", maybe "Docker Profiles", maybe some other profiles, which are all referred to as "Remote Profiles". But I don't see grouping profiles in _local_ and _remote_ too useful.

The reason for having "Shell Profiles" and "SSH Profiles" separately is because they have a different UI - SSH profiles have some additional fields (user, host, port, identity file selector, use mosh, mosh ports). If we want such rich SSH UI - we pretty much have to have separated "SSH Profiles". Similar stands for "SSH Connect" dialog - the only reason for its existence is to have the same rich SSH connect UI.

There's another point of confusion: currently, if a user wants to use some additional CLI arguments with `ssh`, he cannot use "SSH Profiles", but he should go to "Shell Profiles" and enter command and arguments there. Maybe we can improve that by adding one more field in "SSH Profiles" UI: "Additional CLI arguments"?

If you ask me, the perfect solution would be to have only "Shell Profiles", since there you can enter any command you want (`powershell`, `cmd`, `ssh`, `docker`, etc.). Also there you can specify any CLI arguments you want. The only drawback of such solution is that there wouldn't be a rich UI for SSH, but user would have to enter everything in CLI arguments. We would also lose some helpers like pre-filling user name. Such solution would probably be perfect for "advanced" users, and I assume that novices rarely use any terminal app anyway. But on the other hand other SSH apps (like Putty) do have idiot-friendly SSH connection UI...

I hope that now reasoning behind this issue is much clearer to everyone.

**Comment by peske** [comment]
In short: my recommendation for all JumpTrading users: simply completely ignore "SSH Profiles". Use "Shell Profiles" when you want to save a profile (even for `ssh` and `mosh`), and "Quick Launch".

**Comment by cjw296** [comment]
If I type "ssh somehost" in the Quick Launch dialog, does that create a "Shell Profile" or a "SSH Profile"? Note for myself: I don't have to type my username in when I do this, it "just works".

FWIW, the macOS Terminal works as @peske describes: if you want options, you type them, no clicky clicky UI options, so I don't think mac users would be upset to see the back of SSH Profiles. 

To my knowledge, I only have one explicit SSH Profile, all my others have been through Quick Launch.

**Comment by peske** [comment]
@cjw296 

> If I type "ssh somehost" in the Quick Launch dialog, does that create a "Shell Profile" or a "SSH Profile"? Note for myself: I don't have to type my username in when I do this, it "just works".

When you type **any** command in "Quick Launch", including `ssh somehost`, it creates temporary `ShellProfile`, which is used to launch the session, but not saved. `SshProfile` is created only in "SSH Info" dialog. `ShellProfile` is a general profile type that supports any command.

Regarding typing username - as far as I know, you have to type it in "Quick Launch" for `ssh` and `mosh`. In both cases, you need to have `user@host`. I'm confused about how it can _just work_ if you don't type it. It's possible to make such _automation_, but as far as I know, we don't have it yet.

**Comment by cjw296** [comment]
Cool, this all makes sense, not sure this is worth spending time on.
