### ISSUE TITLE
Very low user input responsiveness in case of continious output generation

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#257]
To repro:

1. Launch cmd.exe and run `dir /s` under directory with huge amount of files and directories (any other cli command to generate output constantly will cause the issue as well).
2. While cli command launched as above prints the output, open another tab or window and try to type something. Significant delay between key press and symbol appearing at the screen will happen.

**Comment by MaxRis** [comment]
Hey @felixse ,

it seems that single `AppServiceConnection` used between TrayProcess and UWP app is not enough to transfer huge number of messages full of data.

Have you noticed performance issues related to this?

I'm thinking that to speed up things we might need to have separate communication channel for each terminal session, for example, what about to try to have separate socket communication connection between UWP and TrayProcess per established terminal session? ( https://docs.microsoft.com/en-us/windows/uwp/networking/sockets ).
Technically, it might will help to implement `_terminalsManager.DisplayOutputRequested += _terminalsManager_DisplayOutputRequested; event handling to write into separate socket for each terminal session.

**Comment by felixse** [comment]
AppServiceConnection is afaik the only way to communicate between the Tray and the App. I'm well aware that it's not ideal but I didn't found anything better so far.
I investigated in NamedPipe connections once, but the problem was that the SystemTray was is running outside the App Package context, so I couldn't establish a connection due to the network isolation of the package. I don't know if sockets will face the same restriction. Might be worth a quick spike

**Comment by peske** [comment]
@MaxRis 

> it seems that single `AppServiceConnection` used between TrayProcess and UWP app is not enough to transfer huge number of messages full of data.

Although JSON and TCP/IP currently used for communication are quite a bad solution for transferring binary data, it turned out that the communication wasn't the main bottleneck, as explained https://github.com/jumptrading/FluentTerminal/issues/258

Let's see how my latest improvement in this area (https://github.com/felixse/FluentTerminal/pull/635) will affect this and similar issues.

**Comment by MaxRis** [comment]
duplicate of https://github.com/jumptrading/FluentTerminal/issues/258
