### ISSUE TITLE
Ad hoc mosh support

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#4]
Similar to #3, Fluent should support ad hoc mosh connections.

Using a keyboard shortcut (and a menu item too) pop up a dialog box which allows the user to make an ad hoc mosh connection.

This can hopefully be done without linking the mosh client to the Fluent binary.

**Comment by peske** [comment]
For now I've implemented it by using the [original (_official_) build](https://mosh.org/#getting), because I've had some issues with building mosh-go. Here are the results:
- https://www.youtube.com/watch?v=s3ppVJspV50
- https://www.youtube.com/watch?v=zES9OCrM8N0

It's easy now to switch from the original `mosh-client.exe` to our `mosh-go.exe` once we have it ready. We can retain the original `mosh-client.exe` implementation as a baseline, to always be able to compare our implementation against it.

**Comment by MaxRis** [comment]
MVP mosh support is merged into our fork by PR https://github.com/jumptrading/FluentTerminal/pull/40

**Comment by mjs** [comment]
This has been done.
