### ISSUE TITLE
[PowerShell annoyance] flickering blue bar at the top "Searching for available modules"

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#44]
This isnt really a fluent thing, because you see the same in the stock terminal, but its annoying and I wonder if we can do something about it. 

If you have your home directory (profile) on a network share, there will be a few ms of latency for every access. This causes a blue box to appear saying "Searching for available modules" if you enter a command that does not exist. It flickers for a few ms, then goes away.

I know that powershell is doing this, but I wonder if we could do something to make this look less silly?

**Comment by MaxRis** [comment]
From there https://community.spiceworks.com/topic/1774437-powershell-ise

" the best fix for me was to remove the modules and scripts folders from the WindowsPowerShell folder in MyDocs. I tend to keep everything in the c:\program files\WindowsPowerShell folder.

PowerShell is searching through every location in the PSModulePath Environment variable and looking for a matching command. There is quite  a bit of overhead to this and a slow connection can really exacerbate this."

"One thing that helps a touch is to map your drive using an FQDN instead of NetBIOS, but this will be a minor help."

I can't test myself since don't have similar environment for the moment

**Comment by daviesalex** [comment]
I think this is pretty low priority, so lets just kill this.
