### ISSUE TITLE
Simplify entering Identity file path for New Remote Tab connection dialog

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#46]
Exact way to simplify Identity file path entering should be discussed. (The approach should speed up the flow.)

Probably, we can save the list of Identity files paths on application-wide level in Settings and pre-load them into drop down control in New Remote Tab connection dialog.

**Comment by daviesalex** [comment]
The "browse" path is very not friendly if your home directory is on a network share - it takes many many seconds to actually enter the path you select into the box. We should probably change that.

**Comment by MaxRis** [comment]
As it was mentioned today, properly configured OpenSSH allows to not enter Identity path at all during the connection. It makes sense to arm FT users with tutorial of proper OpenSSH configuration (maybe, link to some tutor? ) and opt out Identity file path selection controls (maybe move to optional and hidden by default). cc: @peske

**Comment by peske** [comment]
Several things to say:

1. If users use the same private key (identity file) for all SSH connections, the file can be simply placed in `C:\Users\<username>\.ssh` dir, in the same way it's done in Linux. In this case the file will be loaded automatically by ssh client, without entering any identity file path in "SSH Info" dialog.
2. I can make "Identity file path" field editable, so that user can paste the path there. If the file resides in `C:\Users\username\.ssh` (if there's more than one identity file), the user can simply paste the file name, without path.
3. Having in mind that users now have two options to save multiple destinations (SSH profiles, and creating shortcuts), chances are that they will rarely need to select the identity file (only for the first access, and then save shortcut / profile).

**Comment by daviesalex** [comment]
I agree with this - the sensible use here is that the user uses one key by default, and if you want to do a different SSH key its a custom field.  A signpost to documentation makes total sense, be it in-app, or a link to something online.

**Comment by peske** [comment]
There's one more thing that I can do regarding this: list all the files from `C:\Users\<username>\.ssh` directory, and basically allow the user three options to select the file:

1. "Browse", as it is right now;
2. List of files from `C:\Users\<username>\.ssh`, allowing him to select one;
3. Allowing user to enter (paste) any path, with implemented _file doesn't exist_ validation.

Please let me know if you want me to implement any of these additional options.

**Comment by peske** [comment]
I've created an upstream PR (https://github.com/felixse/FluentTerminal/pull/419) which makes some improvements to this. Now user can manually enter/paste the path, and in the file resides in the standard SSH directory (`C:\Users\username\.ssh`), the user can omit the path and enter only file name (i.e. `dev_server.key`).

**Comment by peske** [comment]
It can be made more user friendly if I could use editable ComboBox (requires version 1809, and we are still at Fall Creators Update in the project). We'll see what will Felix say about rising the version. If he doesn't accept that, I'll try to find some alternative way...

The idea is to provide user ability to select the file from the list of files in his SSH config dir.

**Comment by mjs** [comment]
This has been addressed
