### ISSUE TITLE
Paste inserting lines

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#7]
ssh to a Linux box, vi a file, and paste a test file from Windows.  Note that it inserts two newlines where there was one previously. Copying removes no newlines.

I've not looked at the code, but my guess is this is at least partially Windows vs UNIX terminators.

**Comment by nikitar020** [comment]
This does not seem a bug because the behavior can be changed in settings:
![изображение](https://user-images.githubusercontent.com/42252263/55564499-3a4adc80-5722-11e9-8cfe-a3751d5b89aa.png)

This just needs to be taken into account by @peske when implementing new profiles - `ssh` and `mosh` profiles should have that setting "Convert to LF" by default.
