### ISSUE TITLE
Add option to log terminal output to file

### ISSUE THREAD

**Issue by anmcconnell** [jumptrading/FluentTerminal#75]
Add a configuration option to enable terminal output logging
When logging is enabled, add an option to specify a log directory

When logging is enabled, for each terminal tab, log all output to a file in the specified directory for the duration of the shell.  Ideally the log filename includes the start time of the shell.  Something like:  `20190509112203-<profile name>-<unique number>.log` or something similar.

**Comment by MaxRis** [comment]
@anmcconnell is it okay if the terminal output will be logged together with sequences codes?
For example, PowerShell's active input line will be logged as:
```
PS C:\Users\max>[0K[18G
```
Such tools as `mosh` or `tmux` redraws screen content using different sequences codes as well all the time.
All the plain text output in the log file will be searchable, but because of above it will be structured oddly and will be not readable good enough.

Have investigated possibility to retrieve terminal output already processed by xterm (without sequences codes). xterm seems [gives access ](https://xtermjs.org/docs/api/terminal/interfaces/ibuffer/#getline) to the raw buffer, but we will need to implement our own logic to calculate difference between "new" and "old" state of the buffer, login on what to send to log file. Because of complexity and lack of clear understanding of how the difference between "new" and "old" buffer states can be calculated to be viewable in log file, dealing with xterm's raw buffer doesn't sound as good idea.

If to think further about log files with all sequences codes inside and possibility to observe log files in comfortable way, it should be achievable to come up with "log file player" feature. Fluent might be able to open previously recorded log files and apply in real time all logged data block by block. It should be more comfortable to observe logs, but depends on final user real use cases of log files.

cc: @mjs @peske

**Comment by anmcconnell** [comment]
@MaxRis for my use case having the sequence codes would be better than having no logs at all.  As a network engineer, the reason I like to preserve logs is to have an audit trail of activity during troubleshooting activities to provide to vendors and other 3rd parties to demonstrate what corrective actions have been taken.  I often need to revisit terminal sessions from several days ago where the terminal session history has been lost.

I think the idea of a "log file player" is a great one.  If I could open logs on a timeline and restore the terminal history so it's easy to copy/paste replayed outputs, that would completely satisify my use case.

**Comment by mjs** [comment]
@anmcconnell if you're already ussing tmux, it might be better to have tmux log the session for you rather than getting FluentTerminal to do it. A log generated this way would avoid all the escape sequences that tmux uses to draw multiple panes and the status line.

This looks like it might help: https://github.com/tmux-plugins/tmux-logging

**Comment by MaxRis** [comment]
@mjs thanks! `mosh` seems does something similar to `tmux`

**Comment by anmcconnell** [comment]
Thanks @mjs and @MaxRis ... I am not using tmux at the moment but it seems like the most elegant way to achieve logging.  Maybe best to close out this issue in favor of steering users who want logging to use tmux instead.

**Comment by daviesalex** [comment]
I did chat to @anmcconnell yesterday; he has a preference for not using tmux. While that is clearly one way to go, i'm not against exploring if we could do some sort simple text output log (putty style). I think if we did that, you would ignore the complexities of mosh/tmux and just dump the raw text (control chars and all) - at least for MVP. Putty has an option like this IIRC

**Comment by MaxRis** [comment]
@daviesalex MVP to try sounds great,

Putty has the option to cut all escape sequences and left only readable text in log file

![2019-06-30_12-10-47-putty-only-printable](https://user-images.githubusercontent.com/1928902/60394647-44695500-9b30-11e9-9385-d0819397fff5.png)

**Comment by MaxRis** [comment]
@anmcconnell could you please try MVP for logging by installing Fluent from there https://ci.appveyor.com/api/buildjobs/msf25ctqdhpdjnxi/artifacts/MsiInstaller%2FFluentTerminalInstaller-v1.1.255.0-b330864.msi

At bottom of General Settings page is available option to turn on/off logging and to select target logs directory.

**Comment by mjs** [comment]
@MaxRis It seems that filtering out escape sequences isn't that hard and can be done with a relatively simple regex: https://stackoverflow.com/a/33925550

Of course, if tmux is being used you'd still see the status bar output, but it might be readable enough.

**Update**: I'm just tried passing a log file through a simple Python program which uses that regex and the output isn't too bad. It might be good to have this as an option.

**Comment by mjs** [comment]
Other comments:
- What is the default log directory if none is provided?
- The text entry field for the log directory should be a little wider.
- Why is there a lot of extra whitespace before the "Enable Logging" setting?
- I wonder if instead of a setting to turn logging on and off globally, there should be a key binding to toggle logging per terminal session? @anmcconnell, what would you prefer here?

**Comment by MaxRis** [comment]
@mjs thank you for noticing these things, as it was discussed, current implementation is just fast MVP to receive feedback on functionality.

> What is the default log directory if none is provided?

Initially it was folder inside installed UWP app directory, but since I've faced unhandled exceptions on run of unit tests to access application directory (seems, unit tests don't init application environment correctly), for MVP I've changed the default directory to empty string.

> The text entry field for the log directory should be a little wider.

The width of text box is depends on entered content currently, but is limited to max width of 250. Might will set the min width the same as max.

> Why is there a lot of extra whitespace before the "Enable Logging" setting?

Have seen this, but haven't investigated yet.

> I wonder if instead of a setting to turn logging on and off globally, there should be a key binding to toggle logging per terminal session? @anmcconnell, what would you prefer here?

Have thought about this as well. It's pretty close to the discussed above "player" functionality. When you can record/open/replay. Makes sense to introduce some visual indicator that terminal tab is recording logs for the moment.

**Comment by MaxRis** [comment]
Found issues are addressed there https://ci.appveyor.com/api/buildjobs/ms8dd5dq2at137y3/artifacts/MsiInstaller%2FFluentTerminalInstaller-v1.1.267.0-abe168e.msi
Also:
- Default log directory is set to C:\Users\%USERNAME%\AppData\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalCache
- "Printable output only" enabled by default option is added to filter out CSI and OSC escape sequences

**Comment by MaxRis** [comment]
Resolved in our fork by PR https://github.com/jumptrading/FluentTerminal/pull/159
